services:
  - type: web
    name: ai-reader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node main.js
    envVars:
      - key: PORT
        value: "10000"  # Optional: Render sets its own PORT, so you can omit this if you want
